#!/usr/bin/env bash
#
# generate-template-catalog.sh
#
# Reads all YAML files from templates/ and generates a VitePress markdown
# page at website/reference/templates.md. Run from the repository root.
#
# Usage:
#   ./website/scripts/generate-template-catalog.sh

set -euo pipefail

TEMPLATES_DIR="templates"
OUTPUT_FILE="website/reference/templates.md"

if [ ! -d "$TEMPLATES_DIR" ]; then
    echo "Error: $TEMPLATES_DIR directory not found. Run this script from the repository root." >&2
    exit 1
fi

# Capitalize first letter of each word, replace hyphens with spaces
capitalize() {
    echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

# Collect and sort categories
mapfile -t categories < <(find "$TEMPLATES_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)

# Count totals
total_templates=0
for cat_dir in "${categories[@]}"; do
    count=$(find "$TEMPLATES_DIR/$cat_dir" -maxdepth 1 -name '*.yaml' -type f | wc -l)
    total_templates=$((total_templates + count))
done

# Begin output
{
    cat <<'HEADER'
---
outline: [2, 3]
---

# Template Catalog

Workflow ships with a library of ready-to-use templates covering common sysadmin, container, Kubernetes, and infrastructure tasks. Use them as starting points or install them directly.

HEADER

    echo "**${#categories[@]} categories, $total_templates templates.**"
    echo ""
    echo "Browse templates in the TUI (\`t\` key) or list them from the CLI:"
    echo ""
    echo '```bash'
    echo 'workflow templates'
    echo 'workflow templates --fetch   # download community templates'
    echo '```'
    echo ""
    echo "---"
    echo ""

    for cat_dir in "${categories[@]}"; do
        cat_name=$(capitalize "$cat_dir")
        mapfile -t files < <(find "$TEMPLATES_DIR/$cat_dir" -maxdepth 1 -name '*.yaml' -type f | sort)
        file_count=${#files[@]}

        echo "## $cat_name ($file_count)"
        echo ""

        for filepath in "${files[@]}"; do
            filename=$(basename "$filepath" .yaml)
            display_name=$(capitalize "$filename")

            # Extract name field (first occurrence)
            yaml_name=$(grep -m1 '^name:' "$filepath" 2>/dev/null | sed 's/^name:[[:space:]]*//' || echo "")
            if [ -n "$yaml_name" ]; then
                display_name="$yaml_name"
            fi

            # Extract description (first occurrence)
            description=$(grep -m1 '^description:' "$filepath" 2>/dev/null | sed 's/^description:[[:space:]]*//' || echo "")

            # Count steps
            step_count=$(grep -c '^\s*- id:' "$filepath" 2>/dev/null || echo "0")

            # Extract variable names (lines matching "  - name:" under variables)
            # Uses a simple approach: find all "  - name:" lines that appear after "variables:"
            variables=""
            in_variables=false
            while IFS= read -r line; do
                if echo "$line" | grep -qE '^variables:'; then
                    in_variables=true
                    continue
                fi
                if [ "$in_variables" = true ]; then
                    if echo "$line" | grep -qE '^\s+- name:'; then
                        var_name=$(echo "$line" | sed 's/.*- name:[[:space:]]*//')
                        if [ -n "$variables" ]; then
                            variables="$variables, \`$var_name\`"
                        else
                            variables="\`$var_name\`"
                        fi
                    elif echo "$line" | grep -qE '^[a-z]'; then
                        # Hit next top-level key, stop scanning
                        in_variables=false
                    fi
                fi
            done < "$filepath"

            echo "### $display_name"
            echo ""
            if [ -n "$description" ]; then
                echo "$description"
                echo ""
            fi
            echo "| | |"
            echo "|---|---|"
            echo "| **File** | \`$filepath\` |"
            echo "| **Steps** | $step_count |"
            if [ -n "$variables" ]; then
                echo "| **Variables** | $variables |"
            fi
            echo ""
        done
    done

    echo "---"
    echo ""
    echo "*This page is auto-generated by \`website/scripts/generate-template-catalog.sh\`.*"

} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE ($total_templates templates in ${#categories[@]} categories)"
