pub mod ai;
pub mod catalog;
pub mod compare;
pub mod config;
pub mod db;
pub mod detect;
pub mod discovery;
pub mod executor;
pub mod history;
pub mod models;
pub mod notify;
pub mod parser;
pub mod template;
pub mod memory;
pub mod sync;
pub mod secrets;
pub mod wizard;
#[cfg(feature = "mcp")]
pub mod mcp;
